/**
 * reportParser.ts
 *
 * Parses the exact report string produced by generateHeuristicReport() in aiService.ts.
 *
 * Actual report format (from aiService.ts source):
 *
 *   DIGITAL SKILLS FOR DECENT WORK
 *   Executive Research Report — Port Harcourt, Rivers State, Nigeria
 *   Generated by AI Data Analyst
 *
 *   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 *   1. EXECUTIVE SUMMARY
 *   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 *   Body text...
 *   • Bullet point
 *
 * Section delimiters are ━━━ lines (U+2501) surrounding a numbered ALL-CAPS title.
 * Line types: bullet (•), blank, or plain text.
 */

export interface ReportLine {
  type: 'bullet' | 'blank' | 'text';
  content: string;
}

export interface ReportSection {
  number: string;   // e.g. "1", "2"
  title: string;    // e.g. "EXECUTIVE SUMMARY"
  lines: ReportLine[];
}

export interface ParsedReport {
  titleBlock: string[];      // Cover lines before first section
  sections: ReportSection[];
}

const DIVIDER_RE = /^━+$/;
const SECTION_HEADER_RE = /^(\d+)\.\s+(.+)$/;

export function parseReport(raw: string): ParsedReport {
  const lines = raw.split('\n').map(l => l.trimEnd());

  const titleBlock: string[] = [];
  const sections: ReportSection[] = [];

  let insideDivider = false;
  let currentSection: ReportSection | null = null;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const isDivider = DIVIDER_RE.test(line.trim());

    if (isDivider) {
      insideDivider = !insideDivider; // toggle state
      continue;
    }

    if (insideDivider) {
      // We are between an opening and closing divider — this is the section header
      const match = SECTION_HEADER_RE.exec(line.trim());
      if (match) {
        if (currentSection) {
          sections.push(currentSection);
        }
        currentSection = {
          number: match[1],
          title: match[2].trim(),
          lines: [],
        };
      }
      continue;
    }

    if (currentSection) {
      // Section body
      if (line.trim() === '') {
        currentSection.lines.push({ type: 'blank', content: '' });
      } else if (line.trim().startsWith('•')) {
        currentSection.lines.push({
          type: 'bullet',
          content: line.trim().replace(/^•\s*/, ''),
        });
      } else {
        currentSection.lines.push({ type: 'text', content: line.trim() });
      }
    } else {
      // Lines before the first section divider are the title block
      titleBlock.push(line);
    }
  }

  // Push the last section if still open
  if (currentSection) {
    sections.push(currentSection);
  }

  return { titleBlock, sections };
}
