"use client";

/**
 * ReportPDF.tsx
 *
 * Renders the parsed report as a @react-pdf/renderer Document.
 *
 * - Zero DOM dependency
 * - Zero html2canvas dependency
 * - Zero Tailwind / CSS color parsing
 * - All colors are plain HEX literals
 * - Pagination is content-driven (never forced)
 */

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from '@react-pdf/renderer';
import { parseReport, ReportSection, ReportLine } from '@/services/reportParser';

// ─── Palette ────────────────────────────────────────────────────────────────
const C = {
  dark:    '#0F172A',
  mid:     '#334155',
  muted:   '#64748B',
  light:   '#94A3B8',
  border:  '#E2E8F0',
  accent:  '#8F1838',
  orange:  '#FD6925',
  white:   '#FFFFFF',
  bg:      '#F8FAFC',
};

// ─── Styles ──────────────────────────────────────────────────────────────────
const S = StyleSheet.create({
  page: {
    fontFamily:      'Helvetica',
    fontSize:        10,
    color:           C.dark,
    backgroundColor: C.white,
    paddingTop:      40,
    paddingBottom:   50,
    paddingLeft:     45,
    paddingRight:    45,
  },

  // Cover
  coverWrapper: {
    flex:           1,
    justifyContent: 'center',
    alignItems:     'center',
  },
  coverTitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize:   26,
    color:      C.accent,
    textAlign:  'center',
    marginBottom: 8,
  },
  coverSubtitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize:   13,
    color:      C.dark,
    textAlign:  'center',
    marginBottom: 4,
  },
  coverMeta: {
    fontSize:  10,
    color:     C.muted,
    textAlign: 'center',
    marginTop: 4,
  },
  coverDivider: {
    width:           80,
    height:          3,
    backgroundColor: C.accent,
    marginVertical:  16,
    alignSelf:       'center',
  },
  coverSDG: {
    fontSize:   9,
    color:      C.light,
    textAlign:  'center',
    marginTop:  24,
    fontFamily: 'Helvetica-Oblique',
  },

  // Section
  sectionWrapper: {
    marginBottom: 18,
  },
  sectionHeaderBar: {
    backgroundColor: C.accent,
    paddingHorizontal: 8,
    paddingVertical:   4,
    marginBottom:      8,
    flexDirection:     'row',
    alignItems:        'center',
  },
  sectionNumber: {
    fontFamily: 'Helvetica-Bold',
    fontSize:   9,
    color:      C.white,
    marginRight: 6,
  },
  sectionTitle: {
    fontFamily: 'Helvetica-Bold',
    fontSize:   10,
    color:      C.white,
    letterSpacing: 0.8,
  },

  // Body content
  bodyText: {
    fontSize:     10,
    color:        C.mid,
    lineHeight:   1.6,
    marginBottom: 4,
  },
  bulletRow: {
    flexDirection:  'row',
    marginBottom:    3,
    paddingLeft:     8,
  },
  bulletDot: {
    fontSize:     10,
    color:        C.orange,
    marginRight:   5,
    lineHeight:   1.6,
  },
  bulletText: {
    flex:       1,
    fontSize:   10,
    color:      C.mid,
    lineHeight: 1.6,
  },

  // Footer
  footer: {
    position:   'absolute',
    bottom:     22,
    left:       45,
    right:      45,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems:    'center',
    borderTopWidth: 1,
    borderTopColor: C.border,
    paddingTop: 6,
  },
  footerLeft: {
    fontSize: 8,
    color:    C.light,
  },
  footerRight: {
    fontSize: 8,
    color:    C.light,
  },
});

// ─── Sub-components ──────────────────────────────────────────────────────────

function CoverPage({ date }: { date: string }) {
  return (
    <Page size="A4" style={S.page}>
      <View style={S.coverWrapper}>
        <Text style={S.coverTitle}>DIGITAL SKILLS FOR DECENT WORK</Text>
        <View style={S.coverDivider} />
        <Text style={S.coverSubtitle}>Executive Research Report</Text>
        <Text style={S.coverMeta}>Port Harcourt, Rivers State, Nigeria</Text>
        <Text style={S.coverMeta}>{date}</Text>
        <Text style={S.coverMeta}>Generated by AI Data Analyst</Text>
        <Text style={S.coverSDG}>
          Aligned with UN Sustainable Development Goals 8 (Decent Work) &amp; 9 (Industry, Innovation and Infrastructure)
        </Text>
      </View>
      <PageFooter date={date} />
    </Page>
  );
}

function PageFooter({ date }: { date: string }) {
  return (
    <View style={S.footer} fixed>
      <Text style={S.footerLeft}>Digital Skills for Decent Work — {date}</Text>
      <Text
        style={S.footerRight}
        render={({ pageNumber, totalPages }) =>
          `Page ${pageNumber} of ${totalPages}`
        }
      />
    </View>
  );
}

function SectionBlock({ section }: { section: ReportSection }) {
  return (
    <View style={S.sectionWrapper} wrap={false}>
      <View style={S.sectionHeaderBar}>
        <Text style={S.sectionNumber}>{section.number}.</Text>
        <Text style={S.sectionTitle}>{section.title}</Text>
      </View>
      <SectionBody lines={section.lines} />
    </View>
  );
}

function SectionBody({ lines }: { lines: ReportLine[] }) {
  return (
    <>
      {lines.map((line, i) => {
        if (line.type === 'blank') return <View key={i} style={{ height: 6 }} />;
        if (line.type === 'bullet') {
          return (
            <View key={i} style={S.bulletRow}>
              <Text style={S.bulletDot}>•</Text>
              <Text style={S.bulletText}>{line.content}</Text>
            </View>
          );
        }
        return (
          <Text key={i} style={S.bodyText}>{line.content}</Text>
        );
      })}
    </>
  );
}

// ─── Main Document ────────────────────────────────────────────────────────────

interface ReportPDFDocumentProps {
  report: string;
  date: string;
}

export function ReportPDFDocument({ report, date }: ReportPDFDocumentProps) {
  const { sections } = parseReport(report);

  // Pack sections onto content pages, 3 sections per page max to avoid overflow
  // @react-pdf/renderer handles page breaks automatically via `wrap` — we just
  // need to group them into pages.
  return (
    <Document
      title="Digital Skills for Decent Work"
      author="AI Data Analyst"
      subject="Digital Readiness Survey Report — Port Harcourt"
    >
      {/* Cover page */}
      <CoverPage date={date} />

      {/* Content page(s) — let renderer paginate automatically */}
      <Page size="A4" style={S.page}>
        {sections.map((section) => (
          <SectionBlock key={section.number} section={section} />
        ))}
        <PageFooter date={date} />
      </Page>
    </Document>
  );
}
